export default {
  id: "fertilizer-pending-agriculture",
  name: "Fertilizer Pending Agriculture Approval",
  description: "Fertilizer service requests awaiting agriculture approval.",
  categoryId: "agriculture",
  subcategoryId: "service-request",
  groupId: "fertilizer",
  order: 2,
  queryModule: "service-request",
  backend: "parquet",
  variants: ["detailed", "summary"],
  variantLabels: { detailed: "Detailed Report", summary: "Summary Report" },
  summaryGroups: ["unit", "sector", "zone", "section"],
  params: [
    { name: "unit", type: "string", sql: "Unit = @unit" },
    { name: "sector", type: "string", sql: "Sector_Name = @sector" },
    { name: "zone", type: "string", sql: "Zone_Name = @zone" },
    { name: "section", type: "string", sql: "Section_Name = @section" },
    { name: "dateFrom", type: "date", sql: "Max_Created_On >= @dateFrom" },
    { name: "dateTo", type: "date", sql: "Max_Created_On < DATEADD(DAY, 1, @dateTo)" },
  ],
};